### ISSUE TITLE
Bit to Byte conversion

### ISSUE THREAD

**Issue by RenePotocnik** [MuriFlavo/Joze_Strucl_Odgovori#2]
[Tukaj](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/blob/fecd56c2ad2b1a87768a7321dc69cc801b240113/README.md?plain=1#L1469) (in se kje drugje) manjka odgovor;
```
3 Bytes == 24 Bits
```

V pomoč ti je lahko ta spletna stran: [Bytes to Bits Conversion](https://www.gbmb.org/bytes-to-bits)

**Comment by MuriFlavo** [comment]
Fixed in the #9 issue.
