### ISSUE TITLE
Nepopolni odgovori

### ISSUE THREAD

**Issue by RenePotocnik** [MuriFlavo/Joze_Strucl_Odgovori#9]
Par odgovorov manjka/prevec/narobnih pri totih TINYINT... vprasanjih (par odgovorov sn jaz narobe odgovoro ampak vidis po resitvah):
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/0f621209-c7d3-47bf-b55c-0c509264c7ff)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/fb09ab87-0efc-415f-9d59-77213d61cbfe)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/df6400b4-df86-489b-9415-5c5b1dc51d88)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/c8a860f1-7ed5-4aac-9f81-2ed370a85616)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/61701b7e-08b1-40d7-bfa8-94d256d9de8a)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/6f834db2-80b8-4932-bafe-d2d43913dda0)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/973b4d59-bff0-4f63-b269-29e336faf3f7)
![image](https://github.com/MuriFlavo/Joze_Strucl_Odgovori/assets/76653181/5e972cd9-0127-4bc5-9261-668c8583e7dc)

**Comment by MuriFlavo** [comment]
V skladu z novo pridobljeno informacijo, sem posodobil vse podatkovne tipe, tako da imajo pravilne odgovore.
